# Generated by Django 5.0.2 on 2024-05-06 15:16

import utils.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflake.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
