# Generated by Django 5.0.2 on 2024-03-12 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_account_number_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_number",
            field=models.BigIntegerField(
                default="2422459236",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
