# Generated by Django 5.0.2 on 2024-03-20 12:36

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_account_number_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_logout",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="account_number",
            field=models.BigIntegerField(
                default="2431606448",
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                null=True, upload_to=accounts.utils.profile_image_path
            ),
        ),
    ]
