# Generated by Django 5.0.2 on 2024-03-12 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("CURRENT", "Current"),
                            ("FIXED DEPOSIT", "Fixed Deposit"),
                        ],
                        default="SAVINGS",
                        max_length=30,
                    ),
                ),
                ("pin", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.BigIntegerField(
                        default="242248103394078",
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        default="DEBIT",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_mode",
                    models.CharField(
                        choices=[
                            ("MOBILE APP TRANSFER", "Mobile App Transfer"),
                            ("USSD TRANSFER", "Ussd Transfer"),
                        ],
                        default="MOBILE APP TRANSFER",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("recipient_bank", models.CharField(max_length=50)),
                ("recipient_number", models.CharField(max_length=10)),
                ("recipient_name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transactions",
                        to="banking.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "debit_credit",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banking.transaction",
                    ),
                ),
            ],
        ),
    ]
