# Generated by Django 5.0.2 on 2024-04-09 13:31

import django.db.models.deletion
import utils.snowflake
import utils.tools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=utils.snowflake.Snowflake.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "account_number",
                    models.BigIntegerField(
                        default=utils.tools.generate_account_number,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("SAVINGS", "Savings"),
                            ("CURRENT", "Current"),
                            ("FIXED DEPOSIT", "Fixed Deposit"),
                        ],
                        default="SAVINGS",
                        max_length=30,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Accounts",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.BigIntegerField(
                        default=utils.tools.generate_transaction_id,
                        editable=False,
                        unique=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        default="DEBIT",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_mode",
                    models.CharField(
                        choices=[
                            ("MOBILE APP TRANSFER", "Mobile App Transfer"),
                            ("USSD TRANSFER", "Ussd Transfer"),
                        ],
                        default="MOBILE APP TRANSFER",
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="banking.account",
                    ),
                ),
                (
                    "sender_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="transactions",
                        to="banking.account",
                    ),
                ),
            ],
            options={
                "db_table": "Transactions",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        default=utils.snowflake.Snowflake.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "debit_credit",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="banking.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "Ledger",
                "abstract": False,
            },
        ),
    ]
