# Generated by Django 5.0.2 on 2024-05-17 07:08

import utils.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflake.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ledger",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflake.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflake.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_mode",
            field=models.CharField(
                choices=[
                    ("MOBILE APP TRANSFER", "Mobile App Transfer"),
                    ("USSD TRANSFER", "Ussd Transfer"),
                    ("AUTO CREDIT", "Auto Credit"),
                ],
                default="MOBILE APP TRANSFER",
                max_length=50,
            ),
        ),
    ]
