# Generated by Django 5.0.2 on 2024-04-14 10:08

import utils.snowflake
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ledger",
            name="timestamp",
        ),
        migrations.AlterField(
            model_name="ledger",
            name="id",
            field=models.BigIntegerField(
                default=utils.snowflake.Snowflake.generate_id,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
